import {
  ArrowRight,
  ArrowUpRight,
  CalendarDays,
  Camera,
  Check,
  Copy,
  ChartColumn,
  CircleCheck,
  CircleHelp,
  Clock,
  CreditCard,
  Download,
  FileChartColumn,
  FileText,
  IdCard,
  Euro,
  ExternalLink,
  House,
  Images,
  Inbox,
  Keyboard,
  KeyRound,
  ListChecks,
  LayoutDashboard,
  LogOut,
  Mail,
  Moon,
  NotebookPen,
  PanelLeft,
  Plus,
  Search,
  Signature,
  Star,
  ShieldCheck,
  Store,
  Sun,
  Timer,
  TreePalm,
  TriangleAlert,
  Upload,
  UserPlus,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

/**
 * Los nombres siguen siendo los del panel: si mañana se cambia de juego de
 * iconos, solo se toca este mapa y no las cuarenta llamadas.
 */
const ICONOS = {
  panel: LayoutDashboard,
  calendario: CalendarDays,
  personas: Users,
  llave: KeyRound,
  enlace: ExternalLink,
  salir: LogOut,
  flecha: ArrowRight,
  diagonal: ArrowUpRight,
  reloj: Clock,
  nota: NotebookPen,
  euro: Euro,
  buscar: Search,
  sol: Sun,
  luna: Moon,
  plegar: PanelLeft,
  casa: House,
  grafico: ChartColumn,
  tarjeta: CreditCard,
  aviso: TriangleAlert,
  estudio: Store,
  mas: Plus,
  bandeja: Inbox,
  ayuda: CircleHelp,
  mensaje: Mail,
  teclado: Keyboard,
  bien: CircleCheck,
  catalogo: Images,
  descargar: Download,
  informe: FileChartColumn,
  consentimiento: ShieldCheck,
  equipo: IdCard,
  ausencias: TreePalm,
  fichaje: Timer,
  firma: Signature,
  estrella: Star,
  documento: FileText,
  checklist: ListChecks,
  subir: Upload,
  alta: UserPlus,
  camara: Camera,
  copiar: Copy,
  hecho: Check,
  cerrar: X,
} satisfies Record<string, LucideIcon>;

export type NombreIcono = keyof typeof ICONOS;

export function Icono({
  nombre,
  className = "",
}: {
  nombre: NombreIcono;
  className?: string;
}) {
  const Svg = ICONOS[nombre];
  return <Svg aria-hidden className={className} strokeWidth={1.75} />;
}
